name: Joke of the Day
on:
  schedule:
    - cron: "0 15 * * *"  # Every day at 3 PM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tell-joke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get a random joke
        id: joke
        run: |
          RESPONSE=$(curl -s -H "Accept: application/json" https://icanhazdadjoke.com/)

          if [ $? -eq 0 ] && echo "$RESPONSE" | jq . > /dev/null 2>&1; then
            JOKE=$(echo "$RESPONSE" | jq -r .joke)
          else
            JOKE="Why don't scientists trust atoms? Because they make up everything!"
          fi

          echo "joke=$JOKE" >> $GITHUB_OUTPUT
          echo "Today's joke: $JOKE"

      - name: Update README with daily joke
        env:
          JOKE: ${{ steps.joke.outputs.joke }}
        run: |
          DATE=$(date '+%A, %B %d, %Y')
          # Use an UNQUOTED heredoc (<<EOF) so shell variables expand here
          cat > README.md <<EOF
# GitHub Actions Course

## 😄 Daily Joke

${DATE}

${JOKE}

---

*This joke is automatically updated daily by GitHub Actions at 3 PM UTC*

## About This Repository

This repository contains examples and exercises for learning GitHub Actions.

### Workflows Included:
- Expressions and Contexts
- External Events
- Manual Triggers
- Scheduled Jobs
- And more!
EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "🤖 Update daily joke - $(date '+%Y-%m-%d')"
          git push
