name: Joke of the Day
on: 
    schedule:
        - cron: "0 15 * * *"  # Every day at 3 PM UTC

    workflow_dispatch:

permissions:
    contents: write

jobs:
    tell-joke:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Get a random joke
              id: joke
              run: |
                # Fetch joke with proper headers and error handling
                RESPONSE=$(curl -s -H "Accept: application/json" https://icanhazdadjoke.com/)
                
                # Check if we got a valid response
                if [ $? -eq 0 ] && echo "$RESPONSE" | jq . > /dev/null 2>&1; then
                  JOKE=$(echo "$RESPONSE" | jq -r .joke)
                else
                  # Fallback joke if API fails
                  JOKE="Why don't scientists trust atoms? Because they make up everything!"
                fi
                
                echo "joke=$JOKE" >> $GITHUB_OUTPUT
                echo "Today's joke: $JOKE"
            
            - name: Update README with daily joke
              run: |
                DATE=$(date '+%A, %B %d, %Y')
                JOKE="${{ steps.joke.outputs.joke }}"
                
                # Create or update README.md
                cat > README.md << EOF
                # GitHub Actions Course
                
                ## 😄 Daily Joke
                
                **$DATE**
                
                > $JOKE
                
                ---
                
                *This joke is automatically updated daily by GitHub Actions at 7 AM UTC*
                
                ## About This Repository
                
                This repository contains examples and exercises for learning GitHub Actions.
                
                ### Workflows Included:
                - Expressions and Contexts
                - External Events
                - Manual Triggers
                - Scheduled Jobs
                - And more!
                
                EOF
            
            - name: Commit and push changes
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add README.md
                git diff --staged --quiet || git commit -m "🤖 Update daily joke - $(date '+%Y-%m-%d')"
                git push
